services:
  web:
    build: .
    ports:
      - 3001:3001
    environment:
      - REDIS_URL=redis://redis
      - JWT_SECRET=keyboard_cat
      - DATABASE_URL=postgresql://postgres:password@postgres/passport-local-jwt?schema=public
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
